### PR TITLE
Rebase docker 

### PR DESCRIPTION
**Pull request by renefritze**
- testing-base moves into https://github.com/dune-community/Dockerfiles
- only unqualified gcc and clang are built

### CODE REVIEW

**Comment by renefritze** [comment]
So the clang builder currently fails because the unqualified clang in jessie is 3.5, which isn't installed. So in light of our discussion yesterday, @ftalbrecht , I think we have two options:
- install and use 3.5 
- set 3.8 names with update-alternatives

**Comment by ftalbrecht** [comment]
If all of our code works with clang-3.5 without a problem, I would opt for using that one. If not, I would opt for 3.8. If I have some time, I can give 3.5 a try...

**Comment by renefritze** [comment]
Well, I could just go ahead and install the clang package in testing-base and see where stuff fails then. No need to check that out manually.

**Comment by renefritze** [comment]
The gdt build is failing in python setup: https://travis-ci.org/dune-community/dune-gdt/jobs/233231422#L1307
That's not new though, AFAICT. @ftalbrecht ?

**Pull request merged**
